/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#0EA5E9",
        "secondary": "#06B6D4",
        "background": "#020B18",
        "surface": "#020B18",
        "surface-dim": "#020B18",
        "surface-container": "#041628",
        "on-surface": "#F0F9FF",
        "on-surface-variant": "#94A3B8",
        "outline": "#64748B",
        "error": "#ffb4ab",
        // Command center colors:
        "tertiary-container": "#ab5100", 
        "inverse-primary": "#2159be",
        "secondary-fixed-dim": "#b6c6f4", 
        "surface-bright": "#373940", 
        "on-error": "#690005", 
        "primary-fixed-dim": "#b0c6ff", 
        "inverse-on-surface": "#2e3037", 
        "on-tertiary": "#522300", 
        "on-error-container": "#ffdad6", 
        "primary-container": "#3366cc", 
        "on-primary": "#002c70", 
        "error-container": "#93000a", 
        "on-tertiary-fixed": "#321300", 
        "surface-container-lowest": "#0b0e14", 
        "surface-variant": "#32353c", 
        "secondary-fixed": "#dae2ff", 
        "on-primary-fixed-variant": "#00419d", 
        "surface-container-highest": "#32353c", 
        "outline-variant": "#434653", 
        "surface-tint": "#b0c6ff", 
        "on-tertiary-container": "#ffe8db", 
        "primary-fixed": "#d9e2ff", 
        "on-secondary-fixed": "#081a3f", 
        "on-primary-container": "#e7ecff", 
        "inverse-surface": "#e1e2eb", 
        "on-secondary-fixed-variant": "#37466d", 
        "on-primary-fixed": "#001945", 
        "tertiary": "#ffb68a", 
        "tertiary-fixed-dim": "#ffb68a", 
        "surface-container-high": "#272a31", 
        "on-tertiary-fixed-variant": "#743500", 
        "secondary-container": "#39486f", 
        "tertiary-fixed": "#ffdbc8", 
        "on-background": "#e1e2eb", 
        "on-secondary": "#1f2f55", 
        "surface-container-low": "#191c22", 
        "on-secondary-container": "#a8b7e5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "2rem",
        "sm": "0.5rem",
        "lg": "1.5rem",
        "xl": "2rem",
        "md": "1rem",
        "2xl": "3rem",
        "margin-mobile": "1rem",
        "gutter": "1.5rem",
        "xs": "0.25rem"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "label-caps": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline": ["Noto Serif"], 
        "display": ["Noto Serif"], 
        "body": ["Inter"], 
        "label": ["Public Sans"]
      },
      fontSize: {
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}
